### ISSUE TITLE
Compatibility with RimNauts 2

### ISSUE THREAD

**Issue by sindre0830** [Vanilla-Expanded/VanillaFactionsExpanded-Pirates#2]
To add compatibility with RimNauts 2, you just need to add `<li>Universum</li>` under `<mods>` here https://github.com/Vanilla-Expanded/VanillaFactionsExpanded-Pirates/blob/main/1.4/Patches/SOS2Patch.xml#L4

It works on the same system as SOS2, so it just needs the EVA tag.

**Comment by Taranchuk** [comment]
It's done
